### ISSUE TITLE
Greek Diacritics

### ISSUE THREAD

**Issue by kerrishotts** [photokandyStudios/gbible#38]
Finding a usable source is difficult. Trying crosswire to see if their modules have it. If not, we may simply be without.

**Comment by AdamDenoon** [comment]
Logos.com has an electronic copy of the Wescott & Hort, Tischendorf, and other copy-and-pastable Greek texts containing diacritics. (Download the logos app for free... Free online copies included)

**Comment by kerrishotts** [comment]
Biblos provided a diacritical version for WH. Whether the ones provided by logos would be suitable in terms of their license would be a question mark for the others. I'll check it out though.

**Comment by kerrishotts** [comment]
v1.1 will have WH diacritics. Will need to come up with a suitable method for searching with those diacritics. I'm not sure if it would be preferable to "strip" the diacritics during search, or require diacritics during search (the latter is obviously easier to program). Furthermore, the transliteration needs to be updated to support the diacritics.

**Comment by kerrishotts** [comment]
Transliteration has been updated to support WH's diacritics; the remainder are punted to 2.0.

**Comment by kerrishotts** [comment]
Searching has been updated in 1.1 to be diacritic and case insensitive. It also handles searching based on transliteration, if enabled, but it's really slow.

**Comment by kerrishotts** [comment]
WH has diacritics. Finding other texts that support diacritics has been nearly impossible. Should I come across a parsed edition of BYZ/TR that supports it, I'll add it.

For now, I'm closing.
