### ISSUE TITLE
(BUG/Feature Error) Strong's Lookup

### ISSUE THREAD

**Issue by AdamDenoon** [photokandyStudios/gbible#45]
In Strong's hierarchy, listings are incorrect. A non-primary word will say "From (G####) and (G####)". These Strong's numbers always match each other and are incorrect.

**Comment by AdamDenoon** [comment]
To clarify: the Strong's numbers are correct, but the words in parentheses "( )" do not reflect the word that the Strong's numbers represent.

**Comment by kerrishotts** [comment]
Thanks for the report. I'm not entirely sure I understand what you're referring to - perhaps give me a specific # and I can see how it compares. The displayed text comes straight from the electronic source, though it is not inconceivable that there are errors there.

**Comment by kerrishotts** [comment]
Comment from @AdamDenoon (in issue #43): As for the Strong's numbers not working, what should say, in Mark 2:4 for example, "εξορύσσω (G1846): from G1537 (εκ) and G3736 (ορύσσω)", it merely repeats the whole word: "εξορύσσω (G1846): from G1537 (εξορύσσω) and G3736 (εξορύσσω)". It would be neat if you could press those root words and get definitions for them right in the app, and Copy and paste from the Strong's Lookup page would be a plus too, for notes/sermon writing purposes, if that's not too difficult. One other thing is the fact that if there's a compound verb (usually containing a prepositional proclitic), trying to get a definition of the second Greek number under it produces no results in the Strong's Lookup.

**Comment by kerrishotts** [comment]
Moved the suggestions above into their own issues.

**Comment by kerrishotts** [comment]
Regarding the Greek word in ()s -- interesting. I will have to check my source text and see if it's the root of the problem or if I did something in the translation to the app that caused the issue. If it's in the source text, I'll have to consider finding another source.

**Comment by kerrishotts** [comment]
Ok -- appears to be a bug in the source document (https://code.google.com/p/open-scriptures/source/browse/trunk/data/strongs-dictionaries/greek/strongs-greek-dictionary.js?r=298) as generated from the script at https://code.google.com/p/open-scriptures/source/browse/trunk/data/strongs-dictionaries/greek/StrongsGreekDictionaryXML-to-JSON.pl?r=298. 

Will have to regenerate sql from original XML.

**Comment by kerrishotts** [comment]
Fixed in latest commit. :-)
