### ISSUE TITLE
UIMenuItem "Define" not working correctly in iOS 6 iPad

### ISSUE THREAD

**Issue by hightech2013** [photokandyStudios/gbible#46]
In the PKBibleViewController.m the following line of code is not working correctly for iOS 6 iPad but it does for iOS 6 iPhone.

ourMenu.menuItems = [NSArray arrayWithObjects: [[UIMenuItem alloc] initWithTitle:@"Define"    action:@selector(defineWord:)],

When "Define" is selected in the iOS 6 iPad simulator we get a popover screen, on which on the top word "Dictionary" and button "Done" are partially not seen. However, when using any other then iOS 6 iPad simulator, everything works fine. I thought you may want to upgrade this app to work correctly with iOS 6 iPad screen when "Define" is selected.

In addition I do have one question. What portion of code actually drives the popover page when "Define" under item menus is selected? That is probably what needs to be updated to support latest iOS 6 iPad screen resolution.

Goodluck.

**Comment by kerrishotts** [comment]
Thanks for the report. The definition view comes straight out of the iOS libraries, but I may have to monkey with the bounding frame a bit.

**Comment by hightech2013** [comment]
That is correct. All you have to do is fix the UIReferenceLibraryViewController bounding for an iPad iOS 6 only.

**Comment by hightech2013** [comment]
Happy Holidays and best of wishes to you on continue developing your apps. It is challenging task that requires a lot of time. But at the end you never know what could be the outcome. Good luck...

**Comment by kerrishotts** [comment]
Fixed by rendering a popup instead.

**Comment by kerrishotts** [comment]
Oh, By the way, I'm not sure if I invited you to the beta test or not. If you'd like to beta test (no pressure, though), just send me your email address at kerrishotts@gmail.com, and I'll send you an invite from TestFlight.
