### ISSUE TITLE
Shadows disappear when switching between Bible and Search/Strongs (and back again)

### ISSUE THREAD

**Issue by kerrishotts** [photokandyStudios/gbible#49]
The shadows are persistent across Settings and About.

Probably just need to call the shadow calculations when the view appears.

Reported by @AdamDenoon.

**Comment by AdamDenoon** [comment]
That sounds like it would work (I run into similar issues consistently...
I'm forgetful lol)

On Wed, Dec 5, 2012 at 4:44 PM, Kerri Shotts notifications@github.comwrote:

> The shadows are persistent across Settings and About.
> 
> Probably just need to call the shadow calculations when the view appears.
> 
> Reported by @AdamDenoon https://github.com/AdamDenoon.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/photokandyStudios/gbible/issues/49.

##

**Comment by kerrishotts** [comment]
Appears fixed as of latest commit.
