### ISSUE TITLE
Add Pasteboard support to Strong'sResults

### ISSUE THREAD

**Issue by kerrishotts** [photokandyStudios/gbible#51]
Requested by @AdamDenoon

This would definitely be handy to have. I'd like to see it in 1.1, though it may be a 2.0 feature if there's not time.

**Comment by AdamDenoon** [comment]
Take your time! Don't worry about rushing (rushing prevents me from having
those random "ah-ha!" moments... or lessens them significantly)

On Wed, Dec 5, 2012 at 5:09 PM, Kerri Shotts notifications@github.comwrote:

> Requested by @AdamDenoon https://github.com/AdamDenoon
> 
> This would definitely be handy to have. I'd like to see it in 1.1, though
> it may be a 2.0 feature if there's not time.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/photokandyStudios/gbible/issues/51.

##

**Comment by kerrishotts** [comment]
For 1.1, a long-press on the row will copy it to the clipboard, and throw an alert. For 2.0 might put this into a menu, along with defining the word underneath, but for now it works.
