### ISSUE TITLE
Allow long-presses on Strong's Numbers in Strong's Search to retrieve definition for the pressed #

### ISSUE THREAD

**Issue by kerrishotts** [photokandyStudios/gbible#52]
Suggested by @AdamDenoon.

Great idea. I'll have to think up a good way to implement it -- it's easy enough in the Bible view because every word (and thus G#) is split out into its own little object. In the search results, however, it's part of a long piece of text, so I'll have to figure out some of the text metrics in order to determine where the user tapped and which part of the text they tapped on. I'd like it to be a v1.1, but probably a v2 feature realistically.

**Comment by AdamDenoon** [comment]
Could you use a table instead of a long line of text, or would that be more
of a pain than using metrics?

On Wed, Dec 5, 2012 at 5:11 PM, Kerri Shotts notifications@github.comwrote:

> Suggested by @AdamDenoon https://github.com/AdamDenoon.
> 
> Great idea. I'll have to think up a good way to implement it -- it's easy
> enough in the Bible view because every word (and thus G#) is split out into
> its own little object. In the search results, however, it's part of a long
> piece of text, so I'll have to figure out some of the text metrics in order
> to determine where the user tapped and which part of the text they tapped
> on. I'd like it to be a v1.1, but probably a v2 feature realistically.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/photokandyStudios/gbible/issues/52.

##

**Comment by kerrishotts** [comment]
Found an open-source drop-in for UILabel that might do this trick... implementing with it to see how it goes. It's at https://github.com/laullon/GLTapLabelDemo

**Comment by kerrishotts** [comment]
Seems to do a good job with a few modifications. In latest commit.

Currently the feature acts on a tap, not a long-press. The long-press is currently being used for the clipboard.
