### ISSUE TITLE
Second Strong's # in Compound Verbs returns no results

### ISSUE THREAD

**Issue by kerrishotts** [photokandyStudios/gbible#53]
Reported by @AdamDenoon

At this point, it's a known issue that I would love to fix. Unfortunately the source I'm using for the text doesn't include those G#s. If you have an idea for a source that does, I'd love to hear about it.

**Comment by AdamDenoon** [comment]
I'm stuck on that one :P Sorry!

On Wed, Dec 5, 2012 at 5:13 PM, Kerri Shotts notifications@github.comwrote:

> Reported by @AdamDenoon https://github.com/AdamDenoon
> 
> At this point, it's a known issue that I would love to fix. Unfortunately
> the source I'm using for the text doesn't include those G#s. If you have an
> idea for a source that does, I'd love to hear about it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/photokandyStudios/gbible/issues/53.

##

**Comment by kerrishotts** [comment]
Moved to 2.0

**Comment by kerrishotts** [comment]
Closing for the time being, since this is addressed by removing these G#s from display in 1.2. Since they are morphological references, they compete with the existing morphology anyway, so I'm not sure how much value they add.

If I find a source that gives me the data for these #s, I'll reconsider at that point.
