### ISSUE TITLE
import operation alert

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#54]
If you go to settings and click on any of the import options, you get an alert "Import Operation Done!" even if you aren't connected to itunes.
So, if you aren't connected the import should fail and show an error instead "Done!"

**Comment by kerrishotts** [comment]
Hmmm. All the import operation does is verify that there's an import.dat file. If there is one, it'll happily import til the cows come home, itunes connected or not. Is there even a way to see if the device is connected to iTunes?

I can't realistically delete the file upon a successful import, as a user may be doing the import by stages. Perhaps if the import file is more than a few minutes old, I could throw a warning and ask the user if they're sure they want to import from an old file...

**Comment by jcesarmobile** [comment]
and when is the import.dat file created? I deleted the app, installed the latest, clicked import and got the "Done!" message. At this point, should the import.dat exists?

Connecting the iPad to itunes, I can see, there is no import.dat before tapping import, it is created when the "Done!" message is shown

**Comment by kerrishotts** [comment]
import.dat should be created by the end-user (using Export, and then renaming the file using itunes), so upon a delete and re-install, yes -- the operation should fail since there is no import.dat. I'll have to fix that up.

**Comment by kerrishotts** [comment]
Fixed. Found out that the code I did have in place was trying to check for a database, but sqlite was creating it automatically -- therefore, no error. I've added error messages now where appropriate, so the user should get a nice notice if they don't have an import.dat file themselves. In current commit.
