### ISSUE TITLE
app crash on settings screen

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#55]
2-3 seconds after entering on the settings screen, the app crash

it was working on the previous release

device: iPad 2 with 5.0.1 and iPod touch 5.1

**Comment by kerrishotts** [comment]
Hm. That shouldn't happen, obviously.

Thanks for the report -- I'll see what's up.

**Comment by kerrishotts** [comment]
Looks like this is the crash report from TestFlight:

-[UITableView setSectionIndexColor:]: unrecognized selector sent to instance 0xc9c5000

0 CoreFoundation 0x37ee38bf **exceptionPreprocess + 163
1 libobjc.A.dylib 0x37a2f1e5 objc_exception_throw + 33
2 CoreFoundation 0x37ee6acb -[NSObject doesNotRecognizeSelector:] + 175
3 CoreFoundation 0x37ee5945 ___forwarding_** + 301
4 CoreFoundation 0x37e40680 **forwarding_prep_0_** + 48
5 gbible 0x000f3bab -[PKSettingsController updateAppearanceForTheme](PKSettingsController.m:60)
6 gbible 0x000f56d5 -[PKSettingsController viewDidAppear:](PKSettingsController.m:298)
7 UIKit 0x319cd6b5 -[UIViewController _setViewAppearState:isAnimating:] + 145
8 UIKit 0x319fb263 -[UINavigationController viewDidAppear:] + 143
9 UIKit 0x319cd6b5 -[UIViewController _setViewAppearState:isAnimating:] + 145
10 UIKit 0x31a28af1 -[UIViewController _endAppearanceTransition:] + 265
11 UIKit 0x31a56ecf -[UIViewController endAppearanceTransition] + 23
12 UIKit 0x319fb115 -[UIViewController _executeAfterAppearanceBlock] + 57
13 UIKit 0x31999e3f _afterCACommitHandler + 175
14 CoreFoundation 0x37eb7b4b __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 19
15 CoreFoundation 0x37eb5d87 __CFRunLoopDoObservers + 259
16 CoreFoundation 0x37eb60e1 __CFRunLoopRun + 761
17 CoreFoundation 0x37e394dd CFRunLoopRunSpecific + 301
18 CoreFoundation 0x37e393a5 CFRunLoopRunInMode + 105
19 GraphicsServices 0x37c10fcd GSEventRunModal + 157
20 UIKit 0x319b9743 UIApplicationMain + 1091
21 gbible 0x000e3a9f main (main.m:16)
22 gbible 0x000dbb48 start + 40

**Comment by kerrishotts** [comment]
Fixed in latest commit.
