### ISSUE TITLE
text overlaps on the search screen

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#56]
![la foto](https://f.cloud.github.com/assets/1637892/20228/bfbb933e-4949-11e2-8f01-e60a7b7d53e8.PNG)

iPad 2 with iOS 5.0.1 and  iPod touch 5.1

**Comment by kerrishotts** [comment]
Ohhhh, that's so not right.

Looks fine on my iPad 3 w/ iOS 6. Maybe it's an iOS 5 deal... Will try on one of those devices.

**Comment by kerrishotts** [comment]
Should be fixed in latest commit.
