### ISSUE TITLE
Highlights work different now?

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#67]
I can't upload a photo right now, but has the highlight changed the way they work?
In previous versions All the text was surrounded by the highlight color, but in the latest version the text isn't highlighted, just the left margin have the highlight color
I'm not sure if it's a bug or a feature

**Comment by kerrishotts** [comment]
Yes; they work differently now. May have an option to switch between the two, but generally, the colors didn't play well on the darker themes, so to keep the text readable, I kept the highlight color from filling the entire background.
