### ISSUE TITLE
Search tab takes a lot of time to load

### ISSUE THREAD

**Issue by jcesarmobile** [photokandyStudios/gbible#75]
STR:
1. Go to search tab
2. Search Jesus
3. Change tab
4. Go back to search tab
( you'll notice that it takes some time to load te tab and the app seems unresponsive)

**Comment by kerrishotts** [comment]
Seems related to searches that return a large # of results. A smaller search doesn't freeze the app when switching to the tab. It may be related to the view recalc'ing all the table row heights... I've got quite a few ideas on changing the search view, so this may go away on its own when I make those changes.

**Comment by kerrishotts** [comment]
Fixed; The search views now store the height of each cell as they are calculated in case they are displayed again. This seems to keep even long searches fast (beyond the initial search, of course).
