### ISSUE TITLE
PKAppDelegate.m missing

### ISSUE THREAD

**Issue by tinalegre** [photokandyStudios/gbible#82]
Dear all,

I'm having some difficulties in running the gbible Xcode Project. More precisely, I get the following error message:

clang: error: no such file or directory: '/Users/xxxx/Documents/xxxxx/gbible/gbible/PKAppDelegate.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

Any ideas/suggestions on that?

**Comment by likenew** [comment]
me too

**Comment by kerrishotts** [comment]
My apologies: I was doing some thing funky with git and it nuked the file. Lovely, right? ;-) I'll see what I can do about getting it back. (You might try the 1.3 branch's version, but it might be too far changed to work on 1.2)

**Comment by kerrishotts** [comment]
Closing for now; I've added the file back to the master branch. Be sure to build with the 1.3 branch if you want the bleeding-edge version that is under development. 

Do let me know if you still have problems compiling 1.2.
