### ISSUE TITLE
No menu items and can't click through

### ISSUE THREAD

**Issue by Stevekav** [photokandyStudios/gbible#83]
hi, i have iPad 1 running ios 5.1.1 and installed version 1.2 after seeing the instructions on your website and the screen shots on itunes. When the app opens, however, it looks like the first screenshot on itunes, but i can't get anything to work, there is not lower menu or buttons with words on them and i can't bring up amy morphology, strongs or anything. What am i doing wrong, missing or is it just not working? I have a koine assignment due next week and this app looked just the thing....pls help!

**Comment by kerrishotts** [comment]
Not entirely sure which screenshots you're referring to: the 1.2 update did away with the tab bar at the bottom of the screen: everything is now accessible via the left-hand sidebar or the "settings" icon on the Bible view. It's possible I missed some of that in the help file, but pretty sure I updated all the screenshots to indicate the change. 

That said, if you long-press on a specific strong's #, you should be able to get a definition for that specific #, or use the left-hand sidebar (tap the "wand" icon) to search strong's.

For regular searching use the "search" icon in either the Bible view or the left-hand sidebar. 

As for morphology, I'm not sure quite what you're referring to: can you not display morphology for a given Greek text (keep in mind the Tischendorf edition is _not_ parsed, and so has no morphology), or can you not get the morphology help file visible? (That's in settings > about > morphology).

**Comment by Stevekav** [comment]
Hi Kerri,

Thank you so much for the wonderful app and all the hard work that has gone into it! 

I originally tapped the word or strongs number and the whole verse was highlighted. I did not realise that the menue that came op on hold was not the normal one - copy, select, select all, but had many more options to it. 

A suggestion for old guys like myself :) is to maybe in the help when a pictire of a button is shown and the actual app has a symbol is to put the symbol in the help, and to mention that one needs to use the right arrow to see the menu items after hold on the word.

Thank you very much

Regards

Steve

sent from iPad

**Comment by kerrishotts** [comment]
Glad that worked for you.

I agree, the menu works very oddly under iOS 5 -- this is something to do with iOS 5 itself. Under iOS 6, the menu is much better on the iPad. There are a few things that don't translate as well to iOS 5 as they do on iOS 6.

The help system itself is going to go under a lot of revision in 1.3, so hopefully that will address any issues with the help files. 

If you have any suggestions or comments in the future, feel free to let me know! If you want to join the beta for 1.3, also let me know (though you do have to put up with an app that's not always stable). The app can always use more testers. :-) (But it's fine if you don't want to beta test, too.)

**Comment by Stevekav** [comment]
Hi Kerri

Hope to upgrade to IOS 6 capable (hate how Apple not upgrading iPad 1!). Happy to beta test. 

Kind regards

Steve
