### ISSUE TITLE
Feature: Localization

### ISSUE THREAD

**Issue by kerrishotts** [photokandyStudios/gbible#9]
Initial v1.0 support is for English only, however other localization would be nice. The question that comes in to play, however, is that the right-side text is English-only, therefore would we need new texts to support localization, such as a French (Louis Segond?) or Spanish version?

**Comment by jcesarmobile** [comment]
I can help with the spanish translation

**Comment by kerrishotts** [comment]
That would be fantastic! 

Also -- do you know of any well-received public-domain (or other nicely licensed) Spanish Language editions for the right-side text? I'm not familiar enough with Spanish to know what's seen as a good translation that would be equivalent to YLT &/or KJV.

**Comment by jcesarmobile** [comment]
I don't know any
According to this web (http://www.biblegateway.com/) there are 14 spanish bibles.

**Comment by kerrishotts** [comment]
Initial localization support is in Build 4775 (latest commit). The Localizable.strings and about.html need translated for each language that we would like to see added. 

@jcesarmobile If you'd like to take a stab at the Spanish translations, I've got a es.lproj folder ready and waiting. :-)

**Comment by jcesarmobile** [comment]
Do I have to translate the Font Names? I'm used to use the english names in other programs, I'm not sure if they have a translation

**Comment by kerrishotts** [comment]
@jcesarmobile Good question -- I wasn't sure how they were dealt with in other languages, so if you're used to seeing the English font names, go ahead and leave them as is. I added it as a "just-in-case" measure... :-)

**Comment by kerrishotts** [comment]
Build 4790 has Polish. :-) Thanks go to @jerryevo.

**Comment by kerrishotts** [comment]
Latest build has Spanish! :-) Thanks to @jcesarmobile.

**Comment by kerrishotts** [comment]
Localization is a never-ending issue; since the app supports it now, I'm going to go ahead and close this issue. Of course, adding additional languages and updating existing ones will always need to be done in the future.
