### ISSUE TITLE
English under Greek

### ISSUE THREAD

**Issue by jackiehaws** [photokandyStudios/gbible#91]
I can not get the English words under the Greek words with the Textus Receptus Greek and King James Version.  What am I doing wrong?  I can get the English words with the Westcott and Hort graham and King James Version.  I purchased this app because it was shown with the English words and did not say it would not work with the Textus Receptus.  

Jackie

**Comment by dabhursin** [comment]
I'm having the same problem. The English words are not under the Greek words?  How do I fix this issue?

**Comment by kerrishotts** [comment]
Which text(s) are you using on the left & and right sides? It's possible that the left-side text you're using doesn't have interlinear glosses. Switch to WHP or download ABP and see if that helps.

**Comment by dabhursin** [comment]
I am using my iPhone 7.  I tried changing the text.  I had no luck. You talked about downloading APB?

**Comment by kerrishotts** [comment]
OK -- go into Settings (tap the gear icon). What do you have set for "Show Translation?"? If it's "No", tap it to switch back to "Yes". You'll have your Greek text set to WHP (Westcott Hort) or ABP (Apostolic Bible Polyglot) to see the translations.

You can download the ABP (Apostolic Bible Polygot) by navigating to Settings (gear icon) > Manage Bibles > Scroll down until you see the ABP & tap it, then download from the resulting screen.

**Comment by dabhursin** [comment]
I think I have it working now. Thank you for your help! I greatly appreciate it. 
David Hursin
